services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana
      POSTGRES_DB: grafana_db
    ports:
      - "5432:5432"  # Changed from 5433 to 5432 to match pipeline expectations
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - data-pipeline-network  # Added network configuration

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - postgres
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - data-pipeline-network  # Added network configuration

# Updated network configuration to reference the existing network by its actual name
networks:
  data-pipeline-network:
    name: docker_data-pipeline-network  # Use the actual network name created by the main docker-compose
    external: true  # This references the network created by the pipeline docker-compose

volumes:
  pgdata:
  grafana_data:
